FROM python:3.10.4

WORKDIR /app

COPY app/frontend_requirements.txt ./frontend_requirements.txt

RUN pip install -r frontend_requirements.txt

RUN pip list > piplist.txt

# override default port (from 8501 to 8080)
ENV STREAMLIT_SERVER_PORT=8080
# these variables might be needed for the right info (logging) to show up in the log
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8

EXPOSE 8080

COPY ./app ./app

WORKDIR /app/app

ENTRYPOINT ["streamlit", "run"]

CMD ["frontend_app.py"]